# Generated by Django 5.0.3 on 2024-03-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_alter_bloodrequest_id'),
        ('donor', '0003_alter_blooddonate_id_alter_donor_id'),
        ('patient', '0002_alter_patient_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodRequest',
            new_name='MyModel',
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
